---
# tasks file for SAS Viya service

- name: Load the {{ role_name }} variables
  include_vars:
    file: "{{ role_name }}"
    name: sas_host_group_variables

- name: Install SAS packages
  include_role:
    name: sas-install

- name: Copy over entrypoint script
  template:
    src: entrypoint
    dest: "{{ SASHOME }}/bin/{{ role_name|lower }}-entrypoint.sh"
    mode: "0755"
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"

- name: Post install build registry
  command: "runuser --shell \"/bin/sh\" --login sas --command \"{{ SPREHOME }}/SASFoundation/utilities/bin/post_install build_registry\" "

- name: Post install build default locale
  command: "runuser --shell \"/bin/sh\" --login sas --command \"{{ SPREHOME }}/SASFoundation/utilities/bin/post_install build_default_locale\" "

- name: Post install build samples config
  command: "runuser --shell \"/bin/sh\" --login sas --command \"{{ SPREHOME }}/SASFoundation/utilities/bin/post_install build_samples_config\" "

- name: Add sas-viya-computeserver as san-dns to cert
  shell: |
    sed -ibak 's/--san-dns localhost \\/--san-dns localhost \\\n        --san-dns sas-viya-computeserver \\/' /opt/sas/viya/home/bin/sas-runlauncher

- name: Set stuff here..
  shell: |
    set -e
    yum install --assumeyes sudo
