---
# tasks file for sas-casserver-primary

- name: Load the {{ role_name }} variables
  include_vars:
    file: "{{ role_name }}"
    name: sas_host_group_variables

- name: Install SAS packages
  include_role:
    name: sas-install

- name: Copy files to remote host
  copy:
    src: "{{ item.name }}"
    dest: "/opt/sas/viya/home/{{ item.path }}/{{ item.name }}"
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"
    mode: "{{ item.mode }}"
  with_items:
  - { name: register_cas.sh, path: "SASFoundation/utilities/bin", mode: "0755" }
  - { name: tenant_setup_docker.sh, path: "bin", mode: "0755" }
  - { name: cas-tls.lua, path: "SASFoundation/utilities/bin", mode: "0755" }

- name: Copy files to remote host - config
  copy:
    src: "{{ item.name }}"
    dest: "/opt/sas/viya/config/{{ item.path }}/{{ item.name }}"
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"
    mode: "{{ item.mode }}"
  with_items:
  - { name: cas-tls.lua, path: "etc/cas/default/", mode: "0755" }

- name: Copy over entrypoint script
  template:
    src: entrypoint
    dest: "{{ SASHOME }}/bin/{{ role_name }}-entrypoint.sh"
    mode: "0755"
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"

- name: Add sas-viya-cas as san-dns to cert
  shell: |
    sed -ibak 's/--san-dns localhost \\/--san-dns localhost \\\n        --san-dns sas-viya-cas \\/' /opt/sas/viya/home/SASFoundation/utilities/bin/cas-tls.sh
    #chown -v sas:sas /opt/sas/viya/config/etc/cas/default/node.lua
    #chmod 0640 /opt/sas/viya/config/etc/cas/default/node.lua
    #mkdir -p /opt/sas/viya/config/etc/cas/default/start.d/
    #chmod 0660 /opt/sas/viya/config/etc/cas/default/start.d/
    #chown root /opt/sas/viya/home/SASFoundation/utilities/bin/caslaunch
    #chmod 4755 /opt/sas/viya/home/SASFoundation/utilities/bin/caslaunch


- name: chown directories
  file: path="{{ item }}" owner="{{ INSTALL_USER }}" group="{{ INSTALL_GROUP }}" state=directory recurse=yes
  with_items:
    - "{{ SAS_CONFIG_ROOT }}/etc/cas/default/permstore"
    - "{{ SAS_CONFIG_ROOT }}//data/cas/"

- name: chown files
  file: path="{{ item }}" owner="{{ INSTALL_USER }}" group="{{ INSTALL_GROUP }}"
  with_items:
    - "{{ SAS_CONFIG_ROOT }}/etc/cas/default/node.lua"

- name: Set stuff here..
  shell: |
    set -e
    yum install --assumeyes sudo
